#!/bin/bash

set -ieu

source ../intelchain/scripts/setup_bls_build_flags.sh

sender='itc17jknjqzzzqwxr6dq95syyahzqx9apjca4rhhff'
receiver='itc1yvhj85pr9nat6g0cwtd9mqhaj3whpgwwyacn6l'
shard_zero='https://testnet.intelchain.network/'
shard_one='https://testnet.intelchain.network/'

direct_node='http://39.127.77.16:9500'

function c {
    printf "%s\n" "$*" | bc
}

# Shard 0 to 0
for iter in $(seq 100); do
    rand=$(grep -m1 -ao '[0-9]' /dev/urandom | sed s/0/3/ | head -n1)
    value=$(c "${iter}/100")
    bump=$(c "${value}+${rand}")
    amount=$(printf "%.2f" ${bump})
    ./itc --node=${shard_zero} \
	  transfer --from ${sender} --to ${receiver} \
	  --from-shard 0 --to-shard 0 --amount ${amount} \
	  --passphrase='' &
done
